// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPersonal_API.Datos;

#nullable disable

namespace WebPersonal_API.Migrations
{
    [DbContext(typeof(PersonalDbContext))]
    [Migration("20240119185833_UsuarioMigracion")]
    partial class UsuarioMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPersonal_API.Modelos.CBarrio", b =>
                {
                    b.Property<string>("CodBarrio")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_barrio")
                        .IsFixedLength();

                    b.Property<string>("CodMunici")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_munici")
                        .IsFixedLength();

                    b.Property<string>("CodProvin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_provin")
                        .IsFixedLength();

                    b.Property<string>("NomBarrio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("nom_barrio");

                    b.HasKey("CodBarrio");

                    b.HasIndex("CodProvin", "CodMunici");

                    b.ToTable("c_barrio", null, t =>
                        {
                            t.HasComment("Barrios");
                        });
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CCatcar", b =>
                {
                    b.Property<string>("CodCatcar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_catcar")
                        .IsFixedLength();

                    b.Property<string>("NomCatcar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("nom_catcar");

                    b.HasKey("CodCatcar");

                    b.ToTable("c_catcar", null, t =>
                        {
                            t.HasTrigger("utr_c_catcar");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CMunici", b =>
                {
                    b.Property<string>("CodProvin")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_provin")
                        .IsFixedLength();

                    b.Property<string>("CodMunici")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_munici")
                        .IsFixedLength();

                    b.Property<string>("NomMunici")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("nom_munici");

                    b.HasKey("CodProvin", "CodMunici");

                    b.ToTable("c_munici", null, t =>
                        {
                            t.HasTrigger("utr_c_munici");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CProvin", b =>
                {
                    b.Property<string>("CodProvin")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("")
                        .HasColumnName("cod_provin")
                        .IsFixedLength();

                    b.Property<string>("NomProvin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("nom_provin");

                    b.HasKey("CodProvin");

                    b.ToTable("c_provin", null, t =>
                        {
                            t.HasTrigger("utr_c_provin");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CBarrio", b =>
                {
                    b.HasOne("WebPersonal_API.Modelos.CProvin", "CodProvinNavigation")
                        .WithMany("CBarrios")
                        .HasForeignKey("CodProvin")
                        .IsRequired()
                        .HasConstraintName("FK_c_barrio_cod_provin");

                    b.HasOne("WebPersonal_API.Modelos.CMunici", "CMunici")
                        .WithMany("CBarrios")
                        .HasForeignKey("CodProvin", "CodMunici")
                        .IsRequired()
                        .HasConstraintName("FK_c_barrio_munici");

                    b.Navigation("CMunici");

                    b.Navigation("CodProvinNavigation");
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CMunici", b =>
                {
                    b.HasOne("WebPersonal_API.Modelos.CProvin", "CodProvinNavigation")
                        .WithMany("CMunicis")
                        .HasForeignKey("CodProvin")
                        .IsRequired()
                        .HasConstraintName("FK_c_munici_cod_provin");

                    b.Navigation("CodProvinNavigation");
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CMunici", b =>
                {
                    b.Navigation("CBarrios");
                });

            modelBuilder.Entity("WebPersonal_API.Modelos.CProvin", b =>
                {
                    b.Navigation("CBarrios");

                    b.Navigation("CMunicis");
                });
#pragma warning restore 612, 618
        }
    }
}
